//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PractiveLabs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int id { get; set; }
        public string name { get; set; }
        public int product_id { get; set; }
        public int user_id { get; set; }
        public decimal price { get; set; }
        public int count { get; set; }
        public decimal sum { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual product product { get; set; }
        public virtual user user { get; set; }
    }
}
